apiVersion: industry-fusion.com/v1alpha4
kind: BeamSqlStatementSet
metadata:
  name: shacl-validation
spec:
  tables:
  - constraint-trigger-table
  - constraint-combination-table
  - attributes
  - alerts-bulk
  - constraint-table
  - entities
  - attributes-insert
  - rdf
  views:
  - attributes-view
  - entities-view
  sqlsettings:
  - table.exec.sink.upsert-materialize: none
  - execution.savepoint.ignore-unclaimed-state: 'true'
  - pipeline.object-reuse: 'true'
  - parallelism.default: '{{ .Values.flink.defaultParalellism }}'
  - table.exec.source.idle-timeout: '{{ .Values.flink.idleTimeout }}'
  - state.backend: rocksdb
  - state.backend.rocksdb.writebuffer.size: 64 kb
  - state.backend.rocksdb.use-bloom-filter: 'true'
  - state.backend.rocksdb.predefined-options: SPINNING_DISK_OPTIMIZED_HIGH_MEM
  - table.exec.state.ttl: '{{.Values.flink.ttl}}'
  sqlstatementmaps:
  - iff/shacl-validation-configmap1
  updateStrategy: none
