name: Nightly

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: private-2
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_PREFIX: ${{ secrets.DOCKER_PREFIX }}
    outputs:
      DOCKER_TAG: ${{ steps.build.outputs.NIGHTLY_DOCKER_TAG }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install jq
        run: sudo apt-get install jq -y

      - id: build
        name: Build & Push Image
        shell: bash
        run: |
          export DOCKER_TAG="latest"
          NIGHTLY_DOCKER_TAG=nightly-`date -I`-`date +%s`

          docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

          docker build -t ${DOCKER_PREFIX}/flink-job-runner:${DOCKER_TAG} -f Dockerfile .

          docker tag ${DOCKER_PREFIX}/flink-job-runner:${DOCKER_TAG} ${DOCKER_PREFIX}/flink-job-runner:${NIGHTLY_DOCKER_TAG}
          docker push ${DOCKER_PREFIX}/flink-job-runner:${DOCKER_TAG}
          docker push ${DOCKER_PREFIX}/flink-job-runner:${NIGHTLY_DOCKER_TAG}
          echo "NIGHTLY_DOCKER_TAG=${NIGHTLY_DOCKER_TAG}" >> "${GITHUB_OUTPUT}"

  deploy:
    needs: build
    uses: IndustryFusion/GitOpsRepo/.github/workflows/deploy.yaml@main
    with:
      APPS: flink-job-runner
      NAMESPACE: flink-job-runner
      DOCKER_TAG: ${{ needs.build.outputs.DOCKER_TAG }}
      CLUSTER: IFF-DEV-DPP-IFRIC
    secrets:
      PRIVATE_GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}